### PR TITLE
Rebase to version 0.3.2

### PR DESCRIPTION
**Pull request by jbirdjavi**
Adds ruby 3.0 support

### CODE REVIEW

**Review by knutsenm — APPROVED** [review]
This looks to be the proper comparison:

https://github.com/Bajena/ams_lazy_relationships/compare/master...CruGlobal:ams_lazy_relationships:rebase032

which I think I understand, but Travis is failing. Do you want to convert to Actions?

**Comment by jbirdjavi** [comment]
The tests were never changed from the original repo, so they're failing due to the code changes made in the fork.

I'd like to know why we ever did this and what problem it solved. This fork caused me about 3 days of extra work.

**Comment by knutsenm** [comment]
@jbirdjavi
https://github.com/CruGlobal/missionhub-api/pull/793

**Comment by jbirdjavi** [comment]
@knutsenm Thanks!

**Pull request merged**
